name: group_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.4

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_storage: ^11.5.0
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.8
  fluttertoast: ^8.2.2
  get: ^4.6.6
  image_picker: ^1.0.4
  intl: ^0.18.1
  permission_handler: ^11.0.1
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
